services:
  db:
    image: postgres:latest
    container_name: expense_tracker_db_container
    restart: always
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DATABASE}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PG_USER} -d expense_tracker_db"]
      interval: 30s
      retries: 5

  api:
    build:
      context: .
      dockerfile: dockerfile
    container_name: expense_tracker_api_container
    restart: always
    environment:
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - db

volumes:
  pgdata: